language: perl

perl:
- "5.28"
  #- "5.26"
  #- "5.24"
  #- "5.22"
- "5.20"
- "5.16"

addons:
  apt:
    packages:
      # From Zonemaster Engine installation instruction
    - autoconf
    - automake
    - build-essential
    - cpanminus
    - libclone-perl
    - libdevel-checklib-perl
    - libfile-sharedir-perl
    - libfile-slurp-perl
    - libidn11-dev
    - libintl-perl
    - libjson-pp-perl
    - liblist-moreutils-perl
    - liblocale-msgfmt-perl
    - libmail-rfc822-address-perl
    - libmodule-find-perl
    - libnet-ip-perl
    - libpod-coverage-perl
    - libreadonly-xs-perl
    - libssl-dev
    - libtest-differences-perl
    - libtest-exception-perl
    - libtest-fatal-perl
    - libtest-pod-perl
    - libtext-csv-perl
    - libtool
    - m4

before_install:
  # Help Perl find modules installed from OS packages
- export PERL5LIB=/usr/share/perl5

  # Zonemaster LDNS needs a newer version of Module::Install
- cpanm Module::Install Module::Install::XSUtil

  # Moose installed from OS package depends on a newer version of Devel::OverloadInfo
- cpanm Devel::OverloadInfo Moose

  # Install Zonemaster LDNS
- git clone --depth=1 --branch=51-ed25519 https://github.com/mattias-p/zonemaster-ldns.git
- ( cd zonemaster-ldns && PERL_CPANM_OPT="--configure-args=--no-ed25519" cpanm . ) && rm -rf zonemaster-ldns
  

before_script:
- cd /home/travis/build/zonemaster/zonemaster-engine
