language: perl
perl:
    - "5.28"
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.16"

before_install:
    - eval $(curl https://travis-perl.github.io/init) --auto
    - sudo apt-get install -y libidn11-dev
    - cpan-install --deps Devel::CheckLib Module::Install Module::Install::XSUtil
    - git clone --depth=1 --branch=$TRAVIS_BRANCH https://github.com/zonemaster/zonemaster-ldns.git
    - cpanm --notest --configure-args="--no-ed25519" ./zonemaster-ldns
