language: perl
perl:
    - "5.28"
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.16"

before_install:
    - eval $(curl https://travis-perl.github.io/init) --auto
    - sudo apt-get install -y libidn11-dev
    - cpan-install --deps Devel::CheckLib Module::Install Module::Install::XSUtil
    - git clone --depth=1 --branch=51-ed25519 https://github.com/mattias-p/zonemaster-ldns.git
    - cpanm --notest --configure-args="--no-ed25519" ./zonemaster-ldns
    - rm -rf zonemaster-ldns

script:
    - perl Makefile.PL
    - make
    - perldoc -lm Zonemaster::Engine
    - echo $PERL5LIB
    - make --trace test
